export const ACTUALIZAR_TDIS = 'ACTUALIZAR_TDIS'
export const ACTUALIZAR_SELECCION_TDI = 'ACTUALIZAR_SELECCION_TDI'


export const ACTUALIZAR_TPUS = 'ACTUALIZAR_TPUS'
export const ACTUALIZAR_SELECCION_TPU = 'ACTUALIZAR_SELECCION_TPU'

export const ACTUALIZAR_ZONS = 'ACTUALIZAR_ZONS'
export const ACTUALIZAR_SELECCION_ZON = 'ACTUALIZAR_SELECCION_ZON'