// types
// REQUEST
export const ESTADO_REQUEST_EXITO           = 'ESTADO_REQUEST_EXITO'
export const ESTADO_REQUEST_NO_AUTORIZADO   = 'ESTADO_REQUEST_NO_AUTORIZADO'
export const ESTADO_REQUEST_NO_EXISTE       = 'ESTADO_REQUEST_NO_EXISTE'
export const ESTADO_REQUEST_ERROR_SERVIDOR  = 'ESTADO_REQUEST_ERROR_SERVIDOR'
export const ESTADO_REQUEST_DESCONOCIDO     = 'ESTADO_REQUEST_DESCONOCIDO'

// SUCURSALES
export const OBTENER_SUCURSALES_USUARIO_EXITO     = 'OBTENER_SUCURSALES_USUARIO_EXITO'
export const OBTENER_SUCURSALES_USUARIO_FAIL      = 'OBTENER_SUCURSALES_USUARIO_FAIL'
export const FILTRO_SELECCIONAR_SUCURSAL_USUARIO  = 'FILTRO_SELECCIONAR_SUCURSAL_USUARIO'

export const OBTENER_SUCURSALES_EXITO         = 'OBTENER_SUCURSALES_EXITO'
export const OBTENER_SUCURSALES_FAIL          = 'OBTENER_SUCURSALES_FAIL'

// FECHAS
export const OBTENER_FECHAS_FILTRO_EXITO = 'OBTENER_FECHAS_FILTRO_EXITO'
export const OBTENER_FECHAS_FILTRO_FAIL  = 'OBTENER_FECHAS_FILTRO_FAIL'

export const FILTRO_SELECCIONAR_FECHA_DIA  = 'FILTRO_SELECCIONAR_FECHA_DIA'
export const FILTRO_SELECCIONAR_FECHA_MES  = 'FILTRO_SELECCIONAR_FECHA_MES'
export const FILTRO_SELECCIONAR_FECHA_ANO  = 'FILTRO_SELECCIONAR_FECHA_ANO'

// VENTAS TPR
export const OBTENER_VENTAS_TPR_EXITO   = 'OBTENER_VENTAS_TPR_EXITO'
export const OBTENER_VENTAS_TPR_FAIL    = 'OBTENER_VENTAS_TPR_FAIL'

// PROMOCIONES
export const OBTENER_PROMOCIONES_EXITO    = 'OBTENER_PROMOCIONES_EXITO'
export const OBTENER_PROMOCIONES_FAIL     = 'OBTENER_PROMOCIONES_FAIL'
export const OBTENER_CANALES_DE_PROMOCIONES_EXITO    = 'OBTENER_CANALES_DE_PROMOCIONES_EXITO'
export const OBTENER_CANALES_DE_PROMOCIONES_FAIL     = 'OBTENER_CANALES_DE_PROMOCIONES_FAIL'

export const ACTUALIZAR_CATEGORIAS_DE_PROMOCIONES = 'OBTENER_PROMOCIONES_FAIL'

// CARGA DE ARCHIVOS 
export const SELECCIONAR_CARGA_DE_ARCHIVOS = 'SELECCIONAR_CARGA_DE_ARCHIVOS'

// TUTORIAL
export const SELECCIONAR_TUTORIAL = 'SELECCIONAR_TUTORIAL'