// types
// REQUEST
export const ESTADO_REQUEST_EXITO           = 'ESTADO_REQUEST_EXITO'
export const ESTADO_REQUEST_NO_AUTORIZADO   = 'ESTADO_REQUEST_NO_AUTORIZADO'
export const ESTADO_REQUEST_NO_EXISTE       = 'ESTADO_REQUEST_NO_EXISTE'
export const ESTADO_REQUEST_ERROR_SERVIDOR  = 'ESTADO_REQUEST_ERROR_SERVIDOR'
export const ESTADO_REQUEST_DESCONOCIDO     = 'ESTADO_REQUEST_DESCONOCIDO'

// SUCURSALES
export const OBTENER_SUCURSALES_USUARIO_EXITO     = 'OBTENER_SUCURSALES_USUARIO_EXITO'
export const OBTENER_SUCURSALES_USUARIO_FAIL      = 'OBTENER_SUCURSALES_USUARIO_FAIL'
export const FILTRO_SELECCIONAR_SUCURSAL_USUARIO  = 'FILTRO_SELECCIONAR_SUCURSAL_USUARIO'
export const REINICIAR_SUCURSALES_USUARIO         = 'REINICIAR_SUCURSALES_USUARIO'

export const OBTENER_SUCURSALES_EXITO   = 'OBTENER_SUCURSALES_EXITO'
export const OBTENER_SUCURSALES_FAIL    = 'OBTENER_SUCURSALES_FAIL'
export const OBTENER_SUCURSALES_USUARIO = 'OBTENER_SUCURSALES_USUARIO'

// ZONAS
export const FILTRO_SELECCIONAR_ZONA_USUARIO = 'FILTRO_SELECCIONAR_ZONA_USUARIO'

// FECHAS
export const OBTENER_FECHAS_FILTRO_EXITO = 'OBTENER_FECHAS_FILTRO_EXITO'
export const OBTENER_FECHAS_FILTRO_FAIL  = 'OBTENER_FECHAS_FILTRO_FAIL'

export const FILTRO_SELECCIONAR_FECHA_DIA  = 'FILTRO_SELECCIONAR_FECHA_DIA'
export const FILTRO_SELECCIONAR_FECHA_MES  = 'FILTRO_SELECCIONAR_FECHA_MES'
export const FILTRO_SELECCIONAR_FECHA_ANO  = 'FILTRO_SELECCIONAR_FECHA_ANO'

export const REINICIAR_FECHAS = 'REINICIAR_FECHAS'

// VENTAS TPR
export const OBTENER_VENTAS_TPR_EXITO   = 'OBTENER_VENTAS_TPR_EXITO'
export const OBTENER_VENTAS_TPR_FAIL    = 'OBTENER_VENTAS_TPR_FAIL'
export const SELECCIONAR_VISTA_VENTAS   = 'SELECCIONAR_VISTA_VENTAS'

export const REINICIAR_VENTASTPR = 'REINICIAR_VENTASTPR'
export const ACTUALIZAR_ESTADO_CARGA_SUCURSAL_VENTAS   = 'ACTUALIZAR_ESTADO_CARGA_SUCURSAL_VENTAS'
export const ACTUALIZAR_ESTADO_CARGA_ZONA_VENTAS   = 'ACTUALIZAR_ESTADO_CARGA_ZONA_VENTAS'

// PROMOCIONES
export const OBTENER_PROMOCIONES_EXITO               = 'OBTENER_PROMOCIONES_EXITO'
export const OBTENER_PROMOCIONES_FAIL                = 'OBTENER_PROMOCIONES_FAIL'
export const OBTENER_CANALES_DE_PROMOCIONES_EXITO    = 'OBTENER_CANALES_DE_PROMOCIONES_EXITO'
export const OBTENER_CANALES_DE_PROMOCIONES_FAIL     = 'OBTENER_CANALES_DE_PROMOCIONES_FAIL'
export const SELECCIONAR_PROMOCION                   = 'SELECCIONAR_PROMOCION'
export const ACTUALIZAR_COLOR_SELECCIONADO_PROMOCION = 'ACTUALIZAR_COLOR_SELECCIONADO_PROMOCION'
export const SELECCIONAR_VISTA_PROMOCION             = 'SELECCIONAR_VISTA_PROMOCION'

export const ACTUALIZAR_CATEGORIAS_DE_PROMOCIONES = 'OBTENER_PROMOCIONES_FAIL'

export const REINICIAR_PROMOCIONES = 'REINICIAR_PROMOCIONES'
export const DESELECCIONAR_PROMOCION = 'DESELECCIONAR_PROMOCION'
export const DESCARGAR_INFORMACION_PROMOCIONES = 'DESCARGAR_INFORMACION_PROMOCIONES'

export const OBTENER_PROMOCIONES_EXCEL = 'OBTENER_PROMOCIONES_EXCEL'
export const OBTENER_PROMOCIONES_EXCEL_ESPECIFICO = 'OBTENER_PROMOCIONES_EXCEL_ESPECIFICO'
export const MOSTRAR_MODAL_INFORMATIVO_PROMOCIONES = 'MOSTRAR_MODAL_INFORMATIVO_PROMOCIONES'
export const ACTUALIZAR_CANALES_DE_PROMOCIONES   = 'ACTUALIZAR_CANALES_DE_PROMOCIONES'
export const ACTIVAR_MODAL_DESCARGAS_PROMOCIONES = 'ACTIVAR_MODAL_DESCARGAS_PROMOCIONES'

// CARGA DE ARCHIVOS 
export const SELECCIONAR_CARGA_DE_ARCHIVOS = 'SELECCIONAR_CARGA_DE_ARCHIVOS'

// TUTORIAL
export const SELECCIONAR_TUTORIAL = 'SELECCIONAR_TUTORIAL'
export const SELECCIONAR_VIDEO_TUTORIAL = 'SELECCIONAR_VIDEO_TUTORIAL'

// CONFIGURACION
    // USUARIOS
    export const OBTENER_USUARIOS_EXITO               = 'OBTENER_USUARIOS_EXITO'
    export const OBTENER_USUARIOS_FAIL                = 'OBTENER_USUARIOS_FAIL'
    export const OBTENER_TIPOS_USUARIOS_EXITO         = 'OBTENER_TIPOS_USUARIOS_EXITO'
    export const ACTUALIZAR_COLUMNAS_TABLA_USUARIOS   = 'ACTUALIZAR_COLUMNAS_TABLA_USUARIOS'
    export const ACTUALIZAR_LISTA_EJECUTIVOS          = 'ACTUALIZAR_LISTA_EJECUTIVOS'
    export const ACTUALIZAR_COLUMNAS_TABLA_EJECUTIVOS = 'ACTUALIZAR_COLUMNAS_TABLA_EJECUTIVOS'
    export const CARGANDO_NUEVO_USUARIO               = 'CARGANDO_NUEVO_USUARIO'
    export const OBTENER_SUCURSALES_X_ZONA            = 'OBTENER_SUCURSALES_X_ZONA'

    // REBATE
    export const MODAL_NUEVO_REBATE   = 'MODAL_NUEVO_REBATE'
    export const AGREGAR_NUEVO_REBATE = 'AGREGAR_NUEVO_REBATE'
    export const OBTUVO_LISTA_REBATE  = 'OBTUVO_LISTA_REBATE'
    export const OBTENER_LISTA_GRUPOS_REBATE  = 'OBTENER_LISTA_GRUPOS_REBATE'
    export const ACTUALIZAR_COLUMNAS_TABLA_REBATE  = 'ACTUALIZAR_COLUMNAS_TABLA_REBATE'
    export const ACTUALIZAR_OBTUVO_REBATE  = 'ACTUALIZAR_OBTUVO_REBATE'
    export const ACTUALIZAR_CARGANDO_TABLA_REBATE  = 'ACTUALIZAR_CARGANDO_TABLA_REBATE'
    export const MODAL_NUEVO_GRUPO_REBATE  = 'MODAL_NUEVO_GRUPO_REBATE'
    export const AGREGAR_NUEVO_GRUPO_REBATE  = 'AGREGAR_NUEVO_GRUPO_REBATE'
    export const ACTUALIZAR_OBTUVO_GRUPO_REBATE  = 'ACTUALIZAR_OBTUVO_GRUPO_REBATE'

    // TIPOS DE USUARIOS
    export const ACTUALIZAR_OBTUVO_TIPOS_USUARIOS           = 'ACTUALIZAR_OBTUVO_TIPOS_USUARIOS'
    export const ACTUALIZAR_DATA_TIPOS_USUARIOS             = 'ACTUALIZAR_DATA_TIPOS_USUARIOS'
    export const ACTUALIZAR_COLUMNAS_TABLA_TIPOS_USUARIOS   = 'ACTUALIZAR_COLUMNAS_TABLA_TIPOS_USUARIOS'
    export const ACTUALIZAR_CARGANDO_TABLA_TIPOS_USUARIOS   = 'ACTUALIZAR_CARGANDO_TABLA_TIPOS_USUARIOS'
    export const ACTUALIZAR_DATA_PERMISOS_TIPO_USUARIO      = 'ACTUALIZAR_DATA_PERMISOS_TIPO_USUARIO'
    export const ACTUALIZAR_CARGANDO_PERMISOS_TIPO_USUARIO  = 'ACTUALIZAR_CARGANDO_PERMISOS_TIPO_USUARIO'

// CONTROL DE ARCHIVOS
export const OBTENER_CONTROL_ARCHIVOS = 'OBTENER_CONTROL_ARCHIVOS'
export const OBTENER_COLUMNAS_CONTROL_ARCHIVOS = 'OBTENER_COLUMNAS_CONTROL_ARCHIVOS'

// CONTROL DE VENTAS
export const OBTENER_ESTADISTICA_XZONA = 'OBTENER_ESTADISTICA_XZONA'

// CONTROL DE PROMOCIONES
export const OBTENER_CONTROL_PROMOCIONES = 'OBTENER_CONTROL_PROMOCIONES'
export const OBTENER_COLUMNAS_CONTROL_PROMOCIONES = 'OBTENER_COLUMNAS_CONTROL_PROMOCIONES'
export const CARGANDO_TABLA_CONTROL_PROMOCIONES = 'CARGANDO_TABLA_CONTROL_PROMOCIONES'


// CONTROL DE SELL OUT
export const OBTENER_NUMEROS_MES = 'OBTENER_NUMEROS_MES'
export const OBTENER_ANIO_SELECCIONADO = 'OBTENER_ANIO_SELECCIONADO'
export const OBTENER_MES_SELECCIONADO = 'OBTENER_MES_SELECCIONADO'
export const OBTENER_TODO_MES = 'OBTENER_TODO_MES'
export const CAPTURAR_MENSAJE_CONTROLSELLOUT = 'CAPTURAR_MENSAJE_CONTROLSELLOUT'

// PERFIL
export const CAMBIAR_ESTADO_EDICION_PERFIL = 'CAMBIAR_ESTADO_EDICION_PERFIL'
export const CAMBIAR_VALOR_INPUT_FORMULARIO_PERFIL = 'CAMBIAR_VALOR_INPUT_FORMULARIO_PERFIL'
export const CARGANDO_PERFIL = 'CARGANDO_PERFIL'